@extends->access

@section->main_content

<div class="row row-centered">
    <div class="col-xs-10 col-md-6 col-lg-4 col-xs-offset-1 col-md-offset-3 col-lg-offset-4 col-centered">
        <div class="big-title">
            <p>404</p>
        </div>
    </div>
</div>


<div class="row row-centered">
    <div class="col-xs-10 col-md-6 col-lg-4 col-xs-offset-1 col-md-offset-3 col-lg-offset-4 col-centered">
        <div class="big-title">
            <a href="/" class="btn btn-warning">Go Back</a>
        </div>
    </div>
</div>