@extends->access

@section->main_content

<div class="row row-centered">
    <div class="col-xs-10 col-md-6 col-lg-4 col-xs-offset-1 col-md-offset-3 col-lg-offset-4 col-centered">
        <div class="big-title">
            <p>TODO list</p>
        </div>
    </div>
</div>


<div class="row row-centered">
    <div class="col-xs-12 col-md-6 col-lg-4 col-lg-offset-2">
        <div class="box">
            <?php // Print all form messages ?>
            <?php if(isset($_SESSION['messageBag'])){ ?>
                <div class="alert alert-danger">
                    <?php
                    foreach ($_SESSION['messageBag'] as $message) {
                        echo '<p>' . $message . '</p>';
                    }
                    ?>
                </div>
            <?php } // end isset messageBag ?>
            <?php unset($_SESSION['messageBag']); ?>

            <form action="/" method="post">
                <div class="form-group">
                    <label for="email">E-mail</label>
                    <input type="email" name="email" id="email" class="form-control" value="<?php echo isset($_SESSION['email']) ? $_SESSION['email'] : ''; unset($_SESSION['email']); ?>">
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" name="password" id="password" class="form-control">
                </div>
                <div class="text-center">
                    <input type="submit" value="Login" class="btn btn-primary">
                </div>
            </form>
        </div>
    </div>

    <div class="col-xs-12 col-md-6 col-lg-4">
        <div class="box">
            <div>
                <p>Want to enjoy beautiful possibilities of this app?</p>
                <p>Register now and make Your life easier and more organized.</p>
            </div>
            <div>
                <a href="/user-create"><button class="btn btn-primary">Register</button></a>
            </div>
        </div>
    </div>
</div>