@extends->access

@section->main_content

<div class="row row-centered">
    <div class="col-xs-10 col-md-6 col-lg-4 col-xs-offset-1 col-md-offset-3 col-lg-offset-4 col-centered">
        <div class="big-title">
            <p>Registration successful!</p>
            <p>Now head over to your email to activate your account.</p>
        </div>
    </div>
</div>


<?php // Print mail contents ?>
<?php if(isset($mailContents)){ ?>
    <div class="row row-centered">
        <div class="col-xs-10 col-md-6 col-lg-4 col-xs-offset-1 col-md-offset-3 col-lg-offset-4 col-centered">
            <div class="alert alert-info">
                <pre><?php var_dump($mailContents); ?></pre>
            </div>
        </div>
    </div>
<?php } // end isset $mailContents ?>