@extends->access

@section->main_content

<div class="row row-centered">
    <div class="col-xs-10 col-md-6 col-lg-4 col-xs-offset-1 col-md-offset-3 col-lg-offset-4 col-centered">
        <div class="big-title">
            <div class="big-title-content">TODO list</div>
        </div>
    </div>
</div>


<?php // Print all form messages ?>
<?php if(isset($_SESSION['messageBag'])){ ?>
    <div class="row row-centered">
        <div class="col-xs-10 col-md-6 col-lg-4 col-xs-offset-1 col-md-offset-3 col-lg-offset-4 col-centered">
            <div class="alert alert-danger">
                <?php
                foreach ($_SESSION['messageBag'] as $message) {
                    echo '<p>' . $message . '</p>';
                }
                ?>
            </div>
        </div>
    </div>
<?php } // end isset messageBag ?>
<?php unset($_SESSION['messageBag']); ?>


<div class="row row-centered">
    <div class="col-xs-10 col-md-6 col-lg-4 col-xs-offset-1 col-md-offset-3 col-lg-offset-4 col-centered">
        <form action="/user-create" method="post">
            <div class="form-group">
                <label for="email">E-mail</label>
                <input type="email" name="email" id="email" class="form-control" value="<?php echo isset($_SESSION['email']) ? $_SESSION['email'] : ''; unset($_SESSION['email']); ?>">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" name="password" id="password" class="form-control">
            </div>
            <div class="form-group">
                <label for="name">Your Name</label>
                <input type="text" name="name" id="name" class="form-control" value="<?php echo isset($_SESSION['name']) ? $_SESSION['name'] : ''; unset($_SESSION['name']); ?>">
            </div>
            <div class="form-group">
                <label for="surname">Your Surname</label>
                <input type="text" name="surname" id="surname" class="form-control" value="<?php echo isset($_SESSION['surname']) ? $_SESSION['surname'] : ''; unset($_SESSION['surname']); ?>">
            </div>
            <div class="text-center">
                <input type="submit" value="Register" class="btn btn-primary">
                <a href="/" class="btn btn-warning">Go Back</a>
            </div>
        </form>
    </div>
</div>